export const mockarticles = {
  "line/BasicLineChart": {
    title: "基础折线图",
    desc: "BasicLineChart<p>title必须是Array</p><p>grid必须是Array</p>",
    data: "基础折线图的数据，是二维结构",
    history: "今天刚刚创建",
  },
  "line/BasicAreaChart": {
    desc: "BasicAreaChart",
    title: "基础面积图",
    data: "基础面积图的数据，是二维结构",
    history: "今天刚刚创建",
  },
  "line/MultiLinesChart": {
    desc: "MultiLinesChart",
    title: "多折线图",
    data: "多折线图的数据，是二维结构",
    history: "今天刚刚创建",
  },
  "line/StackedAreaChart": {
    desc: "StackedAreaChart",
    title: "堆叠面积图",
    data: "33",
    history: "44",
  },
  "line/GradientStackedAreaChart": {
    desc: "GradientStackedAreaChart",
    title: "渐变堆叠面积图",
    data: "33",
    history: "44",
  },
  "line/BumpChart": {
    desc: "BumpChart",
    title: "凹凸图",
    data: "33",
    history: "44",
  },
  "line/TemperatureChangeChart": {
    desc: "TemperatureChangeChart",
    title: "气温变化",
    data: "33",
    history: "44",
  },
  "line/AreaPiecesChart": {
    desc: "AreaPiecesChart",
    title: "折线图高亮面积图",
    data: "33",
    history: "44",
  },
  "line/DataFilterLineChart": {
    desc: "DataFilterLineChart",
    title: "大量数据过滤折线图",
    data: "33",
    history: "44",
  },
  "line/GradientLineChart": {
    desc: "GradientLineChart",
    title: "渐变折线图",
    data: "xAxis是一个数组，不是一个对象，需要单独处理",
    history: "44",
  },
  "line/DistributionOfElectricityChart": {
    desc: "DistributionOfElectricityChart",
    title: "用电量分布图",
    data: "33",
    history: "44",
  },

  "line/RainfallAndEvaporationChart": {
    desc: "RainfallAndEvaporationChart",
    title: "降雨量和蒸发量",
    data: "33",
    history: "44",
  },
  "line/RainfallAndFlowChart": {
    desc: "RainfallAndFlowChart",
    title: "降雨量和流量",
    data: "33",
    history: "44",
  },
  "line/BeijingAQIChart": {
    desc: "BeijingAQIChart",
    title: "北京 AQI",
    data: "33",
    history: "44",
  },
  "line/BarLineChart": {
    desc: "BarLineChart",
    title: "折现柱状组合图",
    data: "33",
    history: "44",
  },
  "line/DoubleXLineChart": {
    desc: "DoubleXLineChart",
    title: "双X轴",
    data: "33",
    history: "44",
  },
  "line/FunctionChart": {
    desc: "FunctionChart",
    title: "函数绘图",
    data: "33",
    history: "44",
  },
  "line/MarkerLineChart": {
    desc: "MarkerLineChart",
    title: "折线图标记点",
    data: "33",
    history: "44",
  },
  "line/StepLineChart": {
    desc: "StepLineChart",
    title: "阶梯折线图",
    data: "33",
    history: "44",
  },
  "bar/BasicBarChart": {
    desc: "BasicBarChart",
    title: "基本柱状图",
    data: "33",
    history: "44",
  },

  "bar/BgcolorBarChart": {
    desc: "BgcolorBarChart",
    title: "柱状图背景色",
    data: "33",
    history: "44",
  },
  "bar/BarColorBarChart": {
    desc: "BarColorBarChart",
    title: "柱状图颜色",
    data: "33",
    history: "44",
  },
  "bar/WaterfallChart": {
    desc: "WaterfallChart",
    title: "瀑布图",
    data: "33",
    history: "44",
  },
  "bar/NegativeValueBarChart": {
    desc: "NegativeValueBarChart",
    title: "正负值柱状图",
    data: "33",
    history: "44",
  },
  "bar/NegativeValueHorizontalBarChart": {
    desc: "NegativeValueHorizontalBarChart",
    title: "正负值多系列条形图",
    data: "33",
    history: "44",
  },
  "bar/RadialPolarBarChart": {
    desc: "RadialPolarBarChart",
    title: "极坐标柱图",
    data: "33",
    history: "44",
  },
  "bar/WorldPopulationBarChart": {
    desc: "WorldPopulationBarChart",
    title: "世界人口条状图",
    data: "33",
    history: "44",
  },
  "bar/RadialPolarAngleBarChart": {
    desc: "RadialPolarAngleBarChart",
    title: "极坐标角度图",
    data: "33",
    history: "44",
  },
  "bar/GradientBarChart": {
    desc: "GradientBarChart",
    title: "渐变色柱状图",
    data: "33",
    history: "44",
  },
  "bar/LabelBarChart": {
    desc: "LabelBarChart",
    title: "柱状图标签",
    data: "33",
    history: "44",
  },
  "bar/StackedColumnChart": {
    desc: "StackedColumnChart",
    title: "堆叠柱状图",
    data: "33",
    history: "44",
  },
  "bar/StackedHorizontalBarChart": {
    desc: "StackedHorizontalBarChart",
    title: "堆叠条形图",
    data: "33",
    history: "44",
  },
  "bar/MultipleYBarChart": {
    desc: "MultipleYBarChart",
    title: "双Y轴折柱混合图",
    data: "33",
    history: "44",
  },
  "bar/RadialPolarStackedBarChart": {
    desc: "RadialPolarStackedBarChart",
    title: "极坐标堆叠图",
    data: "33",
    history: "44",
  },
  "pie/BasicPieChart": {
    desc: "BasicPieChart",
    title: "基本饼图",
    data: "33",
    history: "44",
  },
  "pie/RoundedCornerPieChart": {
    desc: "RoundedCornerPieChart",
    title: "圆角饼图",
    data: "33",
    history: "44",
  },
  "pie/DoughnutChart": {
    desc: "DoughnutChart",
    title: "甜甜圈图",
    data: "33",
    history: "44",
  },
  "pie/HalfDoughnutChart": {
    desc: "HalfDoughnutChart",
    title: "半环图",
    data: "33",
    history: "44",
  },
  "pie/RoseChart": {
    desc: "RoseChart",
    title: "玫瑰图",
    data: "33",
    history: "44",
  },
  "scatter/BasicScatterChart": {
    desc: "BasicScatterChart",
    title: "基本散点图",
    data: "33",
    history: "44",
  },
  "scatter/AnscombeQuartetChart": {
    desc: "AnscombeQuartetChart",
    title: "安斯科目四重奏",
    data: "33",
    history: "44",
  },
  "scatter/ClusterScatterChart": {
    desc: "ClusterScatterChart",
    title: "聚类散点图",
    data: "33",
    history: "44",
  },
  "scatter/PunchCardScatterChart": {
    desc: "PunchCardScatterChart",
    title: "打卡散点图",
    data: "33",
    history: "44",
  },
  "scatter/SingleAxisScatterChart": {
    desc: "SingleAxisScatterChart",
    title: "单轴散点图",
    data: "33",
    history: "44",
  },
  "scatter/LabelRightScatterChart": {
    desc: "LabelRightScatterChart",
    title: "标签右对齐散点图",
    data: "33",
    history: "44",
  },
  "scatter/LabelTopScatterChart": {
    desc: "LabelTopScatterChart",
    title: "标签顶对齐散点图",
    data: "33",
    history: "44",
  },
  "radar/BasicRadarChart": {
    desc: "BasicRadarChart",
    title: "基本雷达图",
    data: "33",
    history: "44",
  },

  "graph/SimpleGraphChart": {
    desc: "graph/SimpleGraphChart",
    title: "基础关系图",
    data: "33",
    history: "44",
  },
  "graph/CartesianGraphChart": {
    desc: "graph/CartesianGraphChart",
    title: "笛卡尔坐标关系图",
    data: "33",
    history: "44",
  },
  "graph/ForceLayoutGraphChart": {
    desc: "graph/ForceLayoutGraphChart",
    title: "力布局关系图",
    data: "33",
    history: "44",
  },
  "graph/CircleLayoutGraphChart": {
    desc: "graph/CircleLayoutGraphChart",
    title: "圆布局关系图",
    data: "33",
    history: "44",
  },

  "tree/l2rTreeChart": {
    desc: "tree/l2rTreeChart",
    title: "从左到右树",
    data: "33",
    history: "44",
  },
  "tree/r2lTreeChart": {
    desc: "tree/r2lTreeChart",
    title: "从右到左树",
    data: "33",
    history: "44",
  },
  "tree/t2bTreeChart": {
    desc: "tree/t2bTreeChart",
    title: "从上到下树",
    data: "33",
    history: "44",
  },
  "tree/b2tTreeChart": {
    desc: "tree/b2tTreeChart",
    title: "从下到上树",
    data: "33",
    history: "44",
  },
  "tree/PolylineTreeChart": {
    desc: "tree/PolylineTreeChart",
    title: "折线树图",
    data: "33",
    history: "44",
  },
  "tree/RadialTreeChart": {
    desc: "tree/RadialTreeChart",
    title: "径向树图",
    data: "33",
    history: "44",
  },
  "parallel/SimpleParallelChart": {
    desc: "parallel/SimpleParallelChart",
    title: "基础平行坐标图",
    data: "33",
    history: "44",
  },
  "parallel/AqiParallelChart": {
    desc: "parallel/AqiParallelChart",
    title: "AQI 平行坐标图",
    data: "33",
    history: "44",
  },
  "sankey/SimpleSankeyChart": {
    desc: "sankey/SimpleSankeyChart",
    title: "基础桑吉图",
    data: "33",
    history: "44",
  },
  "sankey/GradientSankeyChart": {
    desc: "sankey/GradientSankeyChart",
    title: "桑吉图渐变色",
    data: "33",
    history: "44",
  },
  "sankey/LabelLeftSankeyChart": {
    desc: "sankey/LabelLeftSankeyChart",
    title: "桑吉图标签左对齐",
    data: "33",
    history: "44",
  },
  "funnel/SimpleFunnelChart": {
    desc: "funnel/SimpleFunnelChart",
    title: "基础漏斗图",
    data: "33",
    history: "44",
  },
  "funnel/CustomizeFunnelChart": {
    desc: "funnel/CustomizeFunnelChart",
    title: "订制漏斗图",
    data: "33",
    history: "44",
  },
  "funnel/CompareFunnelChart": {
    desc: "funnel/CompareFunnelChart",
    title: "对比漏斗图",
    data: "33",
    history: "44",
  },
  "funnel/MultipleFunnelChart": {
    desc: "funnel/MultipleFunnelChart",
    title: "多个漏斗图",
    data: "33",
    history: "44",
  },
  "river/SimpleRiverChart": {
    desc: "river/SimpleRiverChart",
    title: "基础河流图",
    data: "33",
    history: "44",
  },
  "wordcloud/BasicWordCloudChart": {
    desc: "wordcloud/BasicWordCloudChart",
    title: "基础词云图",
    data: "33",
    history: "44",
  },
  "wordcloud/CustomizeWordCloudChart": {
    desc: "wordcloud/CustomizeWordCloudChart",
    title: "自定义词云图",
    data: "33",
    history: "44",
  },
  "map/SimpleWorldMapChart": {
    desc: "map/SimpleWorldMapChart",
    title: "基础世界地图",
    data: "33",
    history: "44",
  },
};
