export function CompareFunnelChart() {
  const option = {
    columns: [],
    title: [
      {
        show: true,
        text: "对比漏斗图",
        top: "2%",
        left: "50%",
        textAlign: "center",
        textVerticalAlign: "middle",
        textStyle: {
          color: "#000",
          fontSize: 22,
          fontWeight: 600,
          fontFamily: "Microsoft Yahei",
        },
      },
    ],
    tooltip: {
      trigger: "item",
      formatter: "{a} <br/>{b} : {c}%",
    },
    toolbox: {
      show: true,
      orient: "vertical",
      top: "center",
      feature: {
        dataView: { readOnly: false },
        restore: {},
        saveAsImage: {},
      },
    },
    legend: {
      orient: "vertical",
      left: "left",
      textStyle: {},
      fontWeight: {},
      data: ["Prod A", "Prod B", "Prod C", "Prod D", "Prod E"],
    },
    series: [
      {
        name: "Funnel",
        type: "funnel",
        width: "40%",
        height: "45%",
        left: "5%",
        top: "50%",
        funnelAlign: "right",
        data: [
          { value: 60, name: "Prod C" },
          { value: 30, name: "Prod D" },
          { value: 10, name: "Prod E" },
          { value: 80, name: "Prod B" },
          { value: 100, name: "Prod A" },
        ],
      },
      {
        name: "Pyramid",
        type: "funnel",
        width: "40%",
        height: "45%",
        left: "5%",
        top: "5%",
        sort: "ascending",
        funnelAlign: "right",
        data: [
          { value: 60, name: "Prod C" },
          { value: 30, name: "Prod D" },
          { value: 10, name: "Prod E" },
          { value: 80, name: "Prod B" },
          { value: 100, name: "Prod A" },
        ],
      },
      {
        name: "Funnel",
        type: "funnel",
        width: "40%",
        height: "45%",
        left: "55%",
        top: "5%",
        funnelAlign: "left",
        data: [
          { value: 60, name: "Prod C" },
          { value: 30, name: "Prod D" },
          { value: 10, name: "Prod E" },
          { value: 80, name: "Prod B" },
          { value: 100, name: "Prod A" },
        ],
      },
      {
        name: "Pyramid",
        type: "funnel",
        width: "40%",
        height: "45%",
        left: "55%",
        top: "50%",
        sort: "ascending",
        funnelAlign: "left",
        data: [
          { value: 60, name: "Prod C" },
          { value: 30, name: "Prod D" },
          { value: 10, name: "Prod E" },
          { value: 80, name: "Prod B" },
          { value: 100, name: "Prod A" },
        ],
      },
    ],
  };
  return option;
}
