/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicRadarChart: typeof import('./src/pages/charts/radar/BasicRadarChart.vue')['default']
    ChartDesigner: typeof import('./src/pages/charts/ChartDesigner.vue')['default']
    Charts: typeof import('./src/pages/space/Charts.vue')['default']
    ChartViewer: typeof import('./src/pages/charts/ChartViewer.vue')['default']
    Datafiles: typeof import('./src/pages/space/Datafiles.vue')['default']
    Default: typeof import('./src/pages/Default.vue')['default']
    EchartCalendar: typeof import('./src/pages/charts_components/options/EchartCalendar.vue')['default']
    EchartGraphics: typeof import('./src/pages/charts_components/options/EchartGraphics.vue')['default']
    EchartGrid: typeof import('./src/pages/charts_components/options/EchartGrid.vue')['default']
    EchartLegend: typeof import('./src/pages/charts_components/options/EchartLegend.vue')['default']
    EchartRadar: typeof import('./src/pages/charts_components/options/EchartRadar.vue')['default']
    EchartSeriesBar: typeof import('./src/pages/charts_components/series/EchartSeriesBar.vue')['default']
    EchartSeriesFunnel: typeof import('./src/pages/charts_components/series/EchartSeriesFunnel.vue')['default']
    EchartSeriesGraph: typeof import('./src/pages/charts_components/series/EchartSeriesGraph.vue')['default']
    EchartSeriesHeatmap: typeof import('./src/pages/charts_components/series/EchartSeriesHeatmap.vue')['default']
    EchartSeriesLine: typeof import('./src/pages/charts_components/series/EchartSeriesLine.vue')['default']
    EchartSeriesParallel: typeof import('./src/pages/charts_components/series/EchartSeriesParallel.vue')['default']
    EchartSeriesPie: typeof import('./src/pages/charts_components/series/EchartSeriesPie.vue')['default']
    EchartSeriesRadar: typeof import('./src/pages/charts_components/series/EchartSeriesRadar.vue')['default']
    EchartSeriesRiver: typeof import('./src/pages/charts_components/series/EchartSeriesRiver.vue')['default']
    EchartSeriesSankey: typeof import('./src/pages/charts_components/series/EchartSeriesSankey.vue')['default']
    EchartSeriesScatter: typeof import('./src/pages/charts_components/series/EchartSeriesScatter.vue')['default']
    EchartSeriesTree: typeof import('./src/pages/charts_components/series/EchartSeriesTree.vue')['default']
    EchartSeriesWordCloud: typeof import('./src/pages/charts_components/series/EchartSeriesWordCloud.vue')['default']
    EchartTheme: typeof import('./src/pages/charts_components/options/EchartTheme.vue')['default']
    EchartTitle: typeof import('./src/pages/charts_components/options/EchartTitle.vue')['default']
    EchartVisualmap: typeof import('./src/pages/charts_components/options/EchartVisualmap.vue')['default']
    EchartXAxis: typeof import('./src/pages/charts_components/options/EchartXAxis.vue')['default']
    EchartYAxis: typeof import('./src/pages/charts_components/options/EchartYAxis.vue')['default']
    Home: typeof import('./src/pages/Home.vue')['default']
    Index: typeof import('./src/pages/space/Index.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    Metadata: typeof import('./src/pages/space/components/Metadata.vue')['default']
    Profile: typeof import('./src/pages/space/Profile.vue')['default']
    Projects: typeof import('./src/pages/space/Projects.vue')['default']
    ResizeTpl: typeof import('./src/pages/ResizeTpl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/pages/space/Setting.vue')['default']
    ToggleButton: typeof import('./src/pages/charts_components/ToggleButton.vue')['default']
    UpdateOption: typeof import('./src/pages/charts_components/UpdateOption.vue')['default']
    Welcome: typeof import('./src/pages/charts/Welcome.vue')['default']
  }
}
